version: '3.7'
services:

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - postgresql_monitoring

  hammerdb:
    image: tpcorg/hammerdb:latest
    container_name: hammerdb
    volumes:
      - ./hammerdb:/app
    depends_on:
      - db
    networks:
      - postgresql_monitoring

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    command:
      - '--extend.query-path=/etc/postgres_exporter/queries.yaml'
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml
    depends_on:
      - db
    ports:
      - 9187:9187
    networks:
      - postgresql_monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - postgres_exporter
    ports:
      - 9090:9090
    networks:
      - postgresql_monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      db:
        condition: service_started
      prometheus:
        condition: service_started
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    networks:
      - postgresql_monitoring

networks:
  postgresql_monitoring:
    name: postgresql_monitoring
